### ISSUE TITLE
NSInvalidArgumentException

### ISSUE THREAD

**Issue by andrewhavens** [dblandin/motion-blitz#10]
I'm trying this gem for the first time in my RedPotion app. I've added the gem to the Gemfile, bundled, and ran `rake pod:install`. I'm pretty sure that I've installed everything correctly.

However, when I run this code:

    Notifier = Motion::Blitz
    Notifier.show
    Notifier.loading

I end up with this error:

    Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSBundle initWithURL:]: nil URL argument'

What am I doing wrong?

**Comment by dblandin** [comment]
Hey @andrewhavens,

Sorry about the issue you're having with `motion-blitz`!

I'm guessing that the exception you're seeing is coming from [these few lines](https://github.com/TransitApp/SVProgressHUD/blob/e59216252d05bed907d9e32a3baf0ea93cf81c53/SVProgressHUD/SVProgressHUD.m#L277-L279) in the `SVProgressHUD` source code. It seems like `SVProgressHUD` can't find it's asset bundle within your application resources. I believe that `motion-cocoapods` takes care of linking asset bundles for `pod` installed dependencies to the resources folder.

Are you seeing `SVProgressHUD` install successfully when you run `rake pod:install`?

**Comment by andrewhavens** [comment]
By the way, I think you were right about the pod not being installed correctly. I ran `rake newclear` and it solved the problem.
