### ISSUE TITLE
Sometimes does not show

### ISSUE THREAD

**Issue by andrewhavens** [dblandin/motion-blitz#11]
I don't know why this is happening...In some parts of my app, the loading modal is correctly being displayed. However, in a specific part of my app, it is not displaying at all. I'm not sure how SVProgressHUD works under the hood, so I'm not sure how to debug this.

I'm using this exact same code in multiple places in my app:

    Notifier.show
    Notifier.loading
    make_an_api_request do |response|
      # response returned, stop displaying loading icon
      Notifier.dismiss
    end

**Comment by dblandin** [comment]
Hey @andrewhavens,

I believe that `SVProgressHUD` uses its own `UIWindow`, layered on top of your own for notifications. It would be strange for the notifications to be showing up in parts of your app and not others, unless you're layering new `UIWindow`s somewhere.

Also, you shouldn't have to call both `.loading` and `.show`. [Motion::Blitz.loading](https://github.com/dblandin/motion-blitz/blob/master/lib/project/motion-blitz.rb#L35-L37) is a convenience method which calls `.show` with a message of "Loading...".

Does the HUD show up if you have remove the call to `.dismiss`? Wondering if the block is executed so quickly after `.show` or `.loading` is called, that it appears not to show up.

**Comment by andrewhavens** [comment]
I don't remember how I solved this. Probably one of your recommendations. I don't have this issue anymore so I'm going to close this issue.
